import matplotlib.pyplot as plt

diabetes_tweets = open("diabetes_tweets.json", "r", encoding="utf8")
i = 1
tweets = []

testList = [('diabetes', 660), ('idre', 404), ('svmed', 248), ('diabetes1', 144), ('diabetes2', 126), ('Bajen', 100),
            ('dws', 97), ('framtidsbranschen', 95), ('svpol', 68), ('vardpol', 64), ('forskning', 58),
            ('Världsdiabetesdagen', 57), ('hälsa', 56), ('diabetesforskning', 53), ('blodsocker', 50), ('Diabetes', 49),
            ('twittpuck', 47), ('diabetesgalan', 47), ('DiOS', 44), ('wewontrest', 44), ('dmagenda', 42),
            ('iloveresearch', 40), ('världsdiabetesdagen', 38), ('typ1', 36), ('livetmeddiabetes', 33), ('WDD2018', 32),
            ('Almedalen', 32), ('Diabetesgalan', 30), ('dietist', 27), ('kost', 27), ('läkemedel', 27),
            ('vårdiabetes', 27), ('stödforskningen', 26), ('botadiabetes', 26), ('diabetestyp1', 26), ('nyheter', 25),
            ('almedalen', 23), ('diabetesgalan2018', 22), ('insulin', 22), ('välgörenhet', 22), ('recept', 21),
            ('t1d', 21), ('Diamyd', 19), ('springmatsochdiabetes', 19), ('medtechdagen', 19), ('fredag', 19),
            ('vadgörendietist', 18), ('springmats', 18), ('matvanor', 17), ('öppendiabetes', 17), ('levnadsvanor', 17),
            ('helg', 17), ('researchmatters', 16), ('weloveresearch', 16), ('healthcare', 16), ('Brighter', 16),
            ('bajen', 15), ('träning', 15), ('WDD', 14), ('fysiskaktivitet', 14), ('Iloveresearch', 14),
            ('EASD2018', 14), ('görskillnad', 14), ('mat', 14), ('diabetestyp2', 13), ('Expressen', 13),
            ('FreeStyleLibre', 13), ('WorldDiabetesDay', 12), ('Follicum', 12), ('tarmflora', 12), ('hjärtkärl', 12),
            ('svtnyheter', 12), ('middag', 12), ('glooko', 11), ('blodsockerkoll', 11), ('lifescience', 11),
            ('barndiabetesfonden', 10), ('EASD18', 10), ('breadthefuture', 10), ('kvalreg', 10), ('övervikt', 10),
            ('godochnäravård', 10), ('WorldDiabetesDay2018', 9), ('pharmaceuticals', 9), ('aktier', 9),
            ('mdtglobalchamps18', 9), ('extremväder', 9), ('värmebölja', 9), ('t1dlookslikeme', 9), ('DiabetesTyp1', 9),
            ('gamlasedlar', 9), ('Actiste', 9), ('ehälsa', 9), ('08pol', 9), ('innovation', 9), ('eHälsa', 9),
            ('kondition', 8), ('syntolkning', 8), ('register', 8), ('BioStockSwe', 8), ('SweLifeScience', 8),
            ('medtech', 8), ('diet', 8), ('pratapengar', 8), ('type1diabetes', 8), ('kryssning', 8), ('hypoglykemi', 8),
            ('insulinpump', 8), ('apotek', 8), ('stockholm', 8), ('diabetesdebatt', 8), ('NordiskaMedicinpriset', 7),
            ('jul', 7), ('forskasverige', 7), ('DIF', 7), ('migpol', 7), ('nextcell', 7), ('socker', 7),
            ('barndiabetes', 7), ('sjukvården', 7), ('keto', 7), ('lchf', 7), ('t1diabetes', 7), ('vårdpol', 7),
            ('sdriks', 7), ('tyngreartikelarkiv', 7), ('actiste', 7), ('116omdagen', 6), ('sjukförsäkring', 6),
            ('CAM4', 6), ('Stockholm', 6), ('prevention', 6), ('primärvårdsdietist', 6), ('viärÖIS', 6), ('tyrshov', 6),
            ('tillsammans', 6), ('tsos', 6), ('nalledagen', 6), ('DIFhockey', 6), ('Skåne', 6), ('D1', 6),
            ('NMetC2018', 6), ('MatejOresic', 6), ('Medeon', 6), ('fetmaepidemin', 6), ('type1diabetic', 6),
            ('Hälsa', 6), ('Featured', 6), ('fredagsmys', 6), ('fuckdiabetes', 6), ('almedalen2018', 6), ('val2018', 6),
            ('sverige', 6), ('diabeteswellness', 6), ('fetma', 6), ('gratisblodsockerkoll', 6), ('Vårdarenan', 5),
            ('metabolism', 5), ('typ', 5), ('Studie', 5), ('Alzheimer', 5), ('dexcomg6', 5), ('diabetesteamet', 5),
            ('apoteket', 5), ('worlddiabetesday', 5), ('Dietist', 5), ('diabetessyn', 5), ('epigenetik', 5), ('tv3', 5),
            ('vitarasvar', 5), ('tryggvard', 5), ('wdd', 5), ('världsdiabetesdagen2018', 5), ('teddy', 5),
            ('finanstwitter', 5), ('blogger', 5), ('motmintoppform', 5), ('regionjkpg', 5), ('InventingForLife', 5),
            ('sötningsmedel', 5), ('fruktos', 5), ('vegan', 5), ('cancer', 5), ('t2d', 5), ('obesity', 5),
            ('lågkolhydratkost', 5), ('lowcarb', 5), ('familj', 5), ('medtronic', 5), ('DiabetesTyp2', 5),
            ('Blodsocker', 5), ('Insulin', 5), ('resa', 5), ('innovationaward', 5), ('medtech4health', 5),
            ('Almedalen2018', 5), ('hockey', 5), ('egenvård', 5), ('seddivården', 5), ('leifgroopaward', 4),
            ('Roslundtipsar', 4), ('sthlmtech', 4), ('sjukdom', 4), ('Vaerldsdiabetesdagen', 4), ('folkhälsa', 4),
            ('Vasaloppet', 4), ('diabetesdagen', 4), ('kunskap', 4), ('funkpol', 4), ('nalle', 4), ('adhd', 4),
            ('SKL', 4), ('Registerforskning2018', 4), ('Paliativregistret', 4), ('Diabetesregistret', 4),
            ('kommunen', 4), ('influencer', 4), ('aww1', 4), ('tumba', 4), ('Type2', 4), ('diabeteskryssning', 4),
            ('sjukvård', 4), ('fullkorn', 4), ('diabetesförälder', 4), ('konst', 4), ('LCHF', 4), ('nyforskning', 4),
            ('patient', 4), ('vänner', 4), ('Diabetesepidemin', 4), ('lunch', 4), ('blogg', 4), ('andersfrihamn', 4),
            ('borås', 4), ('boras', 4), ('öppenutlysning', 4), ('forskningsanslag', 4), ('diabeteshund', 4),
            ('Behandling', 4), ('tandläkare', 4), ('medicin', 4), ('föreläsning', 4), ('midnattsloppet', 4),
            ('idrottengörsverigestarkare', 4), ('idrotthelalivet', 4), ('hurvetdudet', 4), ('ai', 4),
            ('digitalvård', 4), ('almedalen18', 4), ('Almedalen18', 4), ('T1D', 4), ('fibrer', 3), ('medicinteknik', 3),
            ('tobak', 3), ('biotech', 3), ('ophthalmology', 3), ('retinameeting', 3), ('ITKUNSKAP', 3),
            ('tomorrowspaperstoday', 3), ('vård', 3), ('stress', 3), ('malmö', 3), ('kardmötet', 3), ('Nyheter', 3),
            ('ehealth', 3), ('Studentkaninen', 3), ('Diabeteshanden', 3), ('bajengalan', 3), ('LiU', 3),
            ('Stayingwelluntilacureisfound', 3), ('hållbarnutrition', 3), ('hållbarhälsa', 3), ('livsstil', 3),
            ('kostbehandling', 3), ('livskvalitet', 3), ('DiabetesDay', 3), ('Västervik', 3), ('adamtensta', 3),
            ('kompetens', 3), ('diabetessyntolk', 3), ('water', 3), ('symptomfri', 3), ('bättrehälsa', 3),
            ('tävling', 3), ('ThursdayThoughts', 3), ('bubblebutt', 3), ('beuty', 3), ('bedårande', 3), ('vacker', 3),
            ('cam4halloween', 3), ('LIVE', 3), ('webcam', 3), ('cute', 3), ('camgirl', 3), ('cam4', 3), ('2die4', 3),
            ('diabetesfonden', 3), ('basilika', 3), ('citron', 3), ('lax', 3), ('gluten', 3), ('demens', 3),
            ('dinrost', 3), ('fotboll', 3), ('primärvård', 3), ('PatientExperience', 3),
            ('livskvalitetivärldsklass', 3), ('regionskåne', 3), ('fotsår', 3), ('StockaNews', 3), ('näravård', 3),
            ('stroke', 3), ('börsen', 3), ('HLM3', 3), ('EnoughNCDs', 3), ('lancet', 3), ('NCD', 3), ('Apoteket', 3),
            ('konstikampenmotdiabetes', 3), ('typ2diabetes', 3), ('elevhälsa', 3), ('trötthet', 3), ('Cancer', 3),
            ('diabetesstudie', 3), ('marathon', 3), ('allergier', 3), ('eksem', 3), ('autoimmun', 3),
            ('glutenintolerans', 3), ('typ1diabetes', 3), ('health', 3), ('ögon', 3), ('bg', 3), ('SelfImprovement', 3),
            ('PersonalDevelopment', 3), ('InsulinPump', 3), ('Healthcare', 3), ('LifeLessons', 3), ('Life', 3),
            ('Diabetic', 3), ('Forskning', 3), ('medtronicdiabetes', 3), ('juvenilediabetes', 3), ('jdrf', 3),
            ('type1lookslikeme', 3), ('type1', 3), ('insulinpumper', 3), ('insulinpumps', 3), ('totype1diabetes', 3),
            ('sweden', 3), ('lund', 3), ('vetenskap', 3), ('Danmark', 3), ('Vindkraft', 3), ('Vattenfall', 3),
            ('Östersjön', 3), ('KriegersFlak', 3), ('enzymer', 3), ('sallad', 3), ('springfördiabetes', 3),
            ('systemkollaps', 3), ('screening', 3), ('vårdpådistans', 3), ('smartalösningarinomehälsa', 3),
            ('vårdoperatör', 3), ('ungdiabetes', 3), ('kronisktsjuka', 3), ('monitorering', 3),
            ('livetmeddiabetestyp1', 3), ('matrecept', 3), ('tacksam', 3), ('Diabetesforskning', 3), ('Ramadan', 3),
            ('diabetesfakta', 3), ('Vårdarena2019', 2), ('västerbotten', 2), ('sockerbiten', 2), ('Venezuela', 2),
            ('dexcom', 2), ('testadig', 2), ('sköterskor', 2), ('JävlaSkitsjukdom', 2), ('diabetic', 2), ('ans', 2),
            ('akutneurologiisverige', 2), ('StorstockholmsDiabetesförening', 2), ('regionpol', 2),
            ('socialstyrelsen', 2), ('primarycare', 2), ('servicedogs', 2), ('sollentuna', 2), ('politik', 2),
            ('ksla', 2), ('Repost', 2), ('swgreen', 2), ('nyttigt', 2), ('medtronic670g', 2), ('halmstad', 2),
            ('sockertoppen2019', 2), ('julbord', 2), ('mh18', 2), ('december', 2), ('julmys', 2), ('KTHuniversity', 2),
            ('Wiadomości', 2), ('swecare', 2), ('högtblodtryck', 2), ('hund', 2), ('diabetesawareness', 2),
            ('torsdag', 2), ('Diabeteshjältar', 2), ('dihealthcare', 2), ('kronisksjukdom', 2), ('diabetedagen', 2),
            ('Annexet', 2), ('varberg', 2), ('gisday', 2), ('CES', 2), ('Tarmfloran', 2), ('fuckcancer', 2),
            ('ketodiet', 2), ('bs', 2), ('kostråd', 2), ('sockerintag', 2), ('hjärtakärl', 2), ('vdd', 2),
            ('DiabetesAwareness', 2), ('lingon', 2), ('rödbetor', 2), ('rå', 2), ('ghostmusikalen', 2),
            ('Medicinteknik', 2), ('depression', 2), ('sverigesradio', 2), ('fång', 2), ('insulinresistens', 2),
            ('EMS', 2), ('instagram', 2), ('körmusik', 2), ('diabeteaforskning', 2), ('gossedjur', 2), ('nallar', 2),
            ('sockertoppenif', 2), ('konditionsbloggen', 2), ('digitalisering', 2), ('frosseri', 2), ('lada', 2),
            ('vddskane', 2), ('måbra', 2), ('musik', 2), ('mittliv', 2), ('hållavikten', 2), ('hovet', 2),
            ('Hockeyallsvenskan', 2), ('diabetesvård', 2), ('utbpol', 2), ('mjölk', 2), ('info', 2), ('syn', 2),
            ('viktminskningmedlchf', 2), ('sj', 2), ('viktnedgång', 2), ('lowcarbfood', 2), ('lcjf', 2),
            ('skånesus', 2), ('easd2018', 2), ('baka', 2), ('bakelser', 2), ('Europa', 2), ('TEDDY', 2),
            ('InventingforLife', 2), ('hjärta', 2), ('tv4', 2), ('sd2018', 2), ('bakasockerfritt', 2), ('pt', 2),
            ('barn', 2), ('Hälsoaktiv', 2), ('Patsak2018', 2), ('placering', 2), ('NextCell', 2),
            ('parkinsonpatienter', 2), ('hjärtkärlpatienter', 2), ('diabetespatienter', 2), ('aidspatienter', 2),
            ('cancerpatienter', 2), ('vassleproteinpulver', 2), ('TV4val', 2), ('intuitiveliving', 2),
            ('anticancer', 2), ('antidiabetes', 2), ('antiinflammatorisk', 2), ('sockerfri', 2), ('IHEforum2018', 2),
            ('svpt', 2), ('putospiratas', 2), ('svt', 2), ('artros', 2), ('alzheimer', 2), ('fisk', 2), ('valet', 2),
            ('järnbrist', 2), ('astma', 2), ('glädje', 2), ('lopp', 2), ('sömn', 2), ('celiaki', 2), ('fibromyalgi', 2),
            ('mjölkfritt', 2), ('glutenfritt', 2), ('sjukdomar', 2), ('maninbeige', 2), ('backpacking', 2),
            ('utflykt', 2), ('urbanexploration', 2), ('beige', 2), ('Fetma', 2), ('skl', 2), ('kunskapsstyrning', 2),
            ('attlevameddiabetes', 2), ('läkare', 2), ('mys', 2), ('valet2018', 2), ('nyttjobb', 2),
            ('freestylelibre', 2), ('livet', 2), ('amykress', 2), ('BloodGlucose', 2), ('PersonalGrowth', 2),
            ('ThisHappenedToMe', 2), ('Health', 2), ('Therapy', 2), ('Recognition', 2), ('Neurology', 2),
            ('Rheumatology', 2), ('Insights', 2), ('FuckDiabetes', 2), ('intealladiabetiker', 2), ('Träning', 2),
            ('Kost', 2), ('munhälsa', 2), ('Noaddedsugar', 2), ('Testandtreat', 2), ('sensor', 2), ('långthår', 2),
            ('löpningärlivet', 2), ('löpning', 2), ('träna', 2), ('gravid', 2), ('antibiotika', 2), ('gesundheit', 2),
            ('lammköttbullar', 2), ('brigther', 2), ('eyesurgery', 2), ('typ1diabetiker', 2), ('brobacka', 2),
            ('våffla', 2), ('blekinge', 2), ('bjornborg', 2), ('jogging', 2), ('Stroke', 2), ('Hjärtinfarkt', 2),
            ('autistmamma', 2), ('travel', 2), ('attresameddiabetes', 2), ('klimat', 2), ('diabetiker', 2),
            ('halsa', 2), ('sthlmpol', 2), ('vibrosense', 2), ('sockertoppen', 2), ('DSNs', 2),
            ('inspiringTheNextGen', 2), ('vårdutveckling', 2), ('datadelning', 2), ('gåva', 2), ('autism', 2),
            ('ORdayMSF', 2), ('MilanoSanremo', 1), ('rubinmedical', 1), ('fightdiabetes', 1), ('helahälsan2019', 1),
            ('jävlaskitsjukdom', 1), ('låtsastid', 1), ('uppfuckat', 1), ('tidsomställningen', 1), ('blodglukos', 1),
            ('g6', 1), ('medtronic640g', 1), ('press', 1), ('Spriten', 1), ('KAW100', 1), ('iot', 1), ('mhealth', 1),
            ('vana', 1), ('självdisciplin', 1), ('SwecareRisingStarAward19', 1), ('välfärdsteknik', 1),
            ('framtidenshalsa', 1), ('infovideon', 1), ('type2diabetes', 1), ('plantbased', 1), ('skongress19', 1),
            ('smslutspel', 1), ('skeaik', 1), ('hhc', 1), ('almtuna', 1), ('hv71', 1), ('fbkse', 1), ('rlgifs', 1),
            ('shl', 1), ('mattias_neo', 1), ('rökning', 1), ('liberalerna', 1), ('opinionlive', 1), ('syskon', 1),
            ('diabetesläger', 1), ('diabetesmammorna', 1), ('graviditetsdiabetes', 1), ('personcentreradvård', 1),
            ('omvårdnad', 1), ('arbete', 1), ('kommunpol', 1), ('maraton', 1), ('t1strong', 1), ('löparstyrka', 1),
            ('MENA', 1), ('segereurope', 1), ('motion', 1), ('rördig', 1), ('heltidsjobb', 1), ('flow', 1),
            ('entrepreneur', 1), ('educate', 1), ('chronicdisease', 1), ('sockerbitenontour', 1), ('svantepaabo', 1),
            ('svantepääbo', 1), ('Världshälsodagen', 1), ('alltomdiabetes', 1), ('diabetesappar', 1),
            ('hatadiabetes', 1), ('SFSD', 1), ('SFD', 1), ('Diabetologisktvårmöte', 1), ('wellness', 1),
            ('Linköpinguniversitet', 1), ('ettkommasex', 1), ('wir2019', 1), ('oscarsteatern', 1), ('hjärt', 1),
            ('uutisvahti', 1), ('lindroos', 1), ('druvsocker', 1), ('påsk', 1), ('blodsockerkollen', 1), ('life', 1),
            ('solnacentrum', 1), ('solna', 1), ('lifesolnacentrum', 1), ('vintermöte', 1), ('Yle', 1),
            ('maxikarlstad', 1), ('älskakunden', 1), ('inkludering', 1), ('NationalOreoDay', 1), ('Nyhet', 1),
            ('sd', 1), ('tallin', 1), ('Solna', 1), ('KidneyMonth', 1), ('cgm', 1), ('glukosvärde', 1),
            ('springvasaloppet', 1), ('vasaloppet', 1), ('blodsockerkurva', 1), ('UngMedMS', 1), ('technology', 1),
            ('köpenhamn', 1), ('WeAreNotRare', 1), ('tappadpdm', 1), ('omnipod', 1), ('katt', 1), ('djur', 1),
            ('Sverige', 1), ('Svenska', 1), ('Kalmar', 1), ('pensionärer', 1), ('myndigheter', 1), ('lindhagen', 1),
            ('icamaxi', 1), ('Världsklass', 1), ('swe', 1), ('koffein', 1), ('kaffe', 1), ('diabeteskunskap', 1),
            ('diabeteskost', 1), ('UpsAndDowns', 1), ('Omnipod', 1), ('BergOchDalbana', 1), ('intervju', 1),
            ('professor', 1), ('FörJenny', 1), ('LundUniversity', 1), ('Lund', 1), ('feedingtube', 1),
            ('EhlersDanlosSyndrome', 1), ('EDS', 1), ('sötning', 1), ('stevia', 1), ('insulinkänning', 1), ('uk', 1),
            ('pwd', 1), ('logotyp', 1), ('fötter', 1), ('fotensdag', 1), ('fotvård', 1), ('RingUPSA', 1),
            ('diabetictype1', 1), ('whiplash', 1), ('smärta', 1), ('afaforskning', 1), ('crap', 1),
            ('abbottfreestylelibre', 1), ('Polityka', 1), ('WHO', 1), ('jävligtmycket', 1), ('Diabetiker', 1),
            ('ålanddiabetiker', 1), ('grönsaker', 1), ('broccoli', 1), ('kliniskastudier', 1),
            ('Konferenskliniskastudier', 1), ('rörapåmig', 1), ('tahandommigsjälv', 1), ('nöjdmeddagen', 1),
            ('stegmåluppnått', 1), ('influensatider', 1), ('Rektorifokus', 1), ('sollentunacentrum', 1),
            ('OurGoalToAssist', 1), ('ShutoutDiabetes', 1), ('BlanchissageDiabète', 1), ('gickbra', 1),
            ('alltpåverkar', 1), ('godisräddarliv', 1), ('felräkning', 1), ('intebarataenspruta', 1), ('d1t', 1),
            ('diabetesmamma', 1), ('Bl', 1), ('vården', 1), ('västmanland', 1), ('bblat', 1), ('harbrasocker', 1),
            ('Skärholmen', 1), ('vällingby', 1), ('mumsigt', 1), ('småkakor', 1), ('unnasig', 1), ('PLUS', 1),
            ('skidome', 1), ('laktosintolerant', 1), ('dialysis', 1), ('renalfailure', 1), ('diaverum', 1),
            ('thursday', 1), ('folsyrabrist', 1), ('myckettabletternu', 1), ('inflammation', 1), ('barnmat', 1),
            ('svd', 1), ('självklarhet', 1), ('digitalhealth', 1), ('ehelse', 1), ('eHealth', 1), ('Languages', 1),
            ('Algorithms', 1), ('sentimentanalysis', 1), ('T2D', 1), ('emoticons', 1), ('emojis', 1), ('Twitter', 1),
            ('sarbehandlingssymposium', 1), ('ringp1', 1), ('RoyFares', 1), ('operation', 1), ('diabetesrisk', 1),
            ('Graviditetsdiabetes', 1), ('frågor', 1), ('sköterska', 1), ('sjuksköterska', 1), ('weekend', 1),
            ('chipsfredag', 1), ('trialnet', 1), ('closedloop', 1), ('Länsförsäkringar', 1), ('lufsthlm19', 1),
            ('sällsyntaliv', 1), ('intesomandra', 1), ('bodybikesmart', 1), ('mage', 1), ('axlar', 1), ('värden', 1),
            ('julkakor', 1), ('julmat', 1), ('nyår2019', 1), ('christmas', 1), ('lågtblodsocker', 1),
            ('flertrafikpolisernu', 1), ('blepol', 1), ('present', 1), ('strumpor', 1), ('julklapp', 1), ('rabatt', 1),
            ('transplantation', 1), ('nyktis', 1), ('JIMIN', 1), ('지민', 1), ('Mikronålar', 1), ('jultider', 1),
            ('lucia', 1), ('intervallträning', 1), ('runningmotivation', 1), ('nofilter', 1), ('adventurer', 1),
            ('tomtomrunner', 1), ('tomtom', 1), ('ålandspringer', 1), ('diplomerad', 1), ('jobbasäkertmedläkemedel', 1),
            ('diabete2', 1), ('vinter', 1), ('julstjärnan', 1), ('springmatsjulkalender', 1), ('räknakolhydrater', 1),
            ('countingcarbs', 1), ('carbs', 1), ('kolhydrater', 1), ('braatthakoll', 1), ('News', 1), ('kakor', 1),
            ('fika', 1), ('julfika', 1), ('pepparkakor', 1), ('prostatacancer', 1), ('NYHETER', 1),
            ('tränavarjedag', 1), ('BREAKING', 1), ('njursvikt', 1), ('alzheimers', 1), ('Hjärtattack', 1),
            ('Doktor', 1), ('doktordahlqvist', 1), ('twitter', 1), ('tweetme', 1), ('energi', 1), ('fasta73', 1),
            ('24hfasta', 1), ('juldikt', 1), ('pyssel', 1), ('näring', 1), ('välling', 1), ('njie', 1), ('vegansk', 1),
            ('plantaserad', 1), ('minhistoria', 1), ('Swegreen', 1), ('hälsoteknologi', 1), ('noccoskumtomte', 1),
            ('Styrketräning', 1), ('sydsvenskan', 1), ('diabetesgalan2019', 1), ('BlackFriday', 1), ('Per', 1),
            ('Nonfiction', 1), ('PositiveThinking', 1), ('Journaling', 1), ('Jedi', 1), ('SleepDeprivation', 1),
            ('Clapping', 1), ('Fatalism', 1), ('Freakshowpodcast', 1), ('anemi', 1), ('GAD', 1), ('ångest', 1),
            ('svmat', 1), ('fitness', 1), ('swepol', 1), ('alkohol', 1), ('drwf', 1), ('superfood', 1),
            ('laktosfri', 1), ('milkshake', 1), ('guldmjölk', 1), ('PlötsligtHänderDet', 1), ('örebro', 1),
            ('fördomar', 1), ('diabetesfördomar', 1), ('kämpa', 1), ('Samsung', 1), ('mättande', 1), ('brasamvete', 1),
            ('jämnblodsocker', 1), ('nosugar', 1), ('intolerans', 1), ('diabaetes2', 1), ('järn', 1), ('jelly', 1),
            ('PeterJihde', 1), ('MollySandén', 1), ('BraStart', 1), ('Mellanmål', 1), ('Frukost', 1),
            ('Sockerfrittliv', 1), ('TestandTreat', 1), ('lindabengtzing', 1), ('wiktoriajohansson', 1),
            ('mollysanden', 1), ('dannysaucedo', 1), ('Iloversearch', 1), ('diabetesläkemedel', 1), ('bästagalan', 1),
            ('GåvaTillBarndiabetesfonden', 1), ('Lyckohalsband', 1), ('Kort', 1), ('hälsingland', 1), ('småland', 1),
            ('mattradition', 1), ('ostkakansdag', 1), ('ostkaka', 1), ('40årmdiabetes', 1), ('inflation', 1),
            ('PeterJidhe', 1), ('botadiabetesnu', 1), ('tinaspicoftoday2018', 1), ('världshälsodagen', 1), ('blå', 1),
            ('blue', 1), ('Vimmerby', 1), ('ENDOMETRIOS', 1), ('levermeddiabetestyp1', 1), ('Tv3', 1), ('Linköping', 1),
            ('disbetesgalan2018', 1), ('konditor', 1), ('Jonna', 1), ('viaplay', 1), ('viasat', 1), ('ruedefemme', 1),
            ('TV3', 1), ('Folkhälsa', 1), ('gala', 1), ('TV100', 1), ('hallbarhalsa', 1), ('kista', 1), ('YNWA', 1),
            ('LFC', 1), ('dagensmedicin', 1), ('teamaberg', 1), ('Bergsåker', 1), ('höstbosune', 1), ('WWD2018', 1),
            ('MåBra', 1), ('DiabetesWellness', 1), ('tomasanderssonwij', 1), ('taw', 1), ('Uppsala', 1),
            ('sdriksJag', 1), ('DräneraTräsket', 1), ('Gränby', 1), ('klimatet', 1), ('feminism', 1), ('aktuellt', 1),
            ('DRWFDiabetes', 1), ('röl', 1), ('regionorebrolan', 1), ('P2', 1), ('medpol', 1), ('Typ1Diabetes', 1),
            ('GABA', 1), ('AkademiskaSjukhuset', 1), ('Diabetesstudie', 1), ('d1', 1), ('digitalsuccé', 1),
            ('detlillasjukhuset', 1), ('SjukhusetiArvika', 1), ('halverasockret', 1), ('kostfonden', 1),
            ('frisktliv', 1), ('BUS', 1), ('NewProfilePic', 1), ('diabeteswellnesssverige', 1), ('volontär', 1),
            ('maloueftertio', 1), ('Diabetesgalan2018', 1), ('dj18', 1), ('matchtröja', 1), ('idrott', 1), ('sport', 1),
            ('gratis', 1), ('förhjärtat', 1), ('kämparpå', 1), ('Apollo', 1), ('SkånesUniversitetssjukhus', 1),
            ('Sjukvård', 1), ('AndreasEdsfeldt', 1), ('mjölkprodukter', 1), ('diabetsgalan', 1), ('diabets', 1),
            ('typ2', 1), ('risken', 1), ('minska', 1), ('IamOff', 1), ('Diabetesfonden', 1), ('BeSayDo', 1),
            ('BättreTillsammans', 1), ('FridaBoisen', 1), ('övervinna', 1), ('DiabetesMonth', 1), ('norrtälje', 1),
            ('norrteljetidning', 1), ('nt', 1), ('diabetesfi', 1), ('svenskadagen', 1), ('chalmersftw', 1),
            ('avancez', 1), ('jointheråvolution', 1), ('drickrå', 1), ('själ', 1), ('kropp', 1), ('Diet', 1),
            ('TypeOnetoTypeNONE', 1), ('ökadLivskvalitet', 1), ('Medtronic', 1), ('Insulinpump', 1), ('nedstämdhet', 1),
            ('hampaolja', 1), ('festmiddag', 1), ('goldenhits', 1), ('störmigpåfelaktigadetaljer', 1), ('radio', 1),
            ('alltidhögpånatten', 1), ('alexStoraDag', 1), ('halloween', 1), ('djungelboken', 1), ('diabetesmannen', 1),
            ('hippocampusdagen', 1), ('Hippocampusdagen', 1), ('jagharviljan', 1), ('jagtogbeslutet', 1),
            ('viktminskning', 1), ('sundmat', 1), ('levautanattdö', 1), ('blosocker', 1), ('djurgården', 1),
            ('attendo', 1), ('HealthforAll', 1), ('äventyr', 1), ('nallensdag', 1), ('allsvenskan', 1),
            ('fredgasmys', 1), ('personcentrerat', 1), ('utveckling', 1), ('skoltwitter', 1), ('singelforever', 1),
            ('crosstrainer', 1), ('ÄlskadeHusdjur', 1), ('kamp', 1), ('strävan', 1), ('Vaccin', 1), ('Sjuk', 1),
            ('Komplikationer', 1), ('Influensa', 1), ('siffror', 1), ('statistik', 1), ('diabetesförbundet', 1),
            ('hba1c', 1), ('vårdcentral', 1), ('kontroll', 1), ('dm', 1), ('sjuksköterskestudent', 1),
            ('robertwells', 1), ('cardio', 1), ('iw24h', 1), ('autumn2018', 1), ('staypositive', 1), ('friskvård', 1),
            ('sittups', 1), ('armhävningar', 1), ('chins', 1), ('mysigt', 1), ('höst', 1), ('chockladmuffin', 1),
            ('muffin', 1), ('choklad', 1), ('cancervård', 1), ('botacancer', 1), ('vaccin', 1), ('influensa', 1),
            ('tumbakicken', 1), ('sommarjob', 1), ('detaljhandel', 1), ('sköldkörtel', 1), ('mejeriintolerans', 1),
            ('överkänslighet', 1), ('intoleranser', 1), ('äträtt', 1), ('njuter', 1), ('kostdoktorn', 1),
            ('dietdoctor', 1), ('nydagidag', 1), ('nuggets', 1), ('mcdonalds', 1), ('lchfmat', 1), ('dajm', 1),
            ('astrid', 1), ('point', 1), ('VibroSense', 1), ('Vibrametri', 1), ('HbA1c', 1), ('ACT', 1),
            ('beteendeanalys', 1), ('swedishaba', 1), ('mätare', 1), ('furthertogether', 1), ('rivercentre', 1),
            ('minnstagram', 1), ('twincitiesinmotion', 1), ('novo', 1), ('kaninteätavadjagvilllängre', 1),
            ('hatarmindiabetes', 1), ('artist', 1), ('Gladys', 1), ('sus', 1), ('bönor', 1), ('curry', 1),
            ('swedishfika', 1), ('Finwire', 1), ('NovoNordisk', 1), ('runningiceland', 1), ('iceland', 1),
            ('visiticeland', 1), ('kanel', 1), ('bullar', 1), ('kanelbullensdag', 1), ('kanelbulle', 1), ('hint', 1),
            ('BästOfGlenn', 1), ('Hälsotrender', 1), ('DaibetesTyp2', 1), ('diplom', 1), ('stockholmmarathon', 1),
            ('EASD', 1), ('warbergic', 1), ('Hemköp', 1), ('bokmässan2018', 1), ('forskartorget', 1), ('Metformin', 1),
            ('attspringameddiabetes', 1), ('dramaqueen', 1), ('mariawern', 1), ('dinosaurier', 1), ('Historia', 1),
            ('Wilhem', 1), ('antiken', 1), ('hälsosam', 1), ('träningärbraförsockret', 1), ('tidningsutdelare', 1),
            ('asperger', 1), ('äppletsdag', 1), ('äpple', 1), ('Forza', 1), ('lågkolhydratskost', 1),
            ('akademibokhandeln', 1), ('RUFF', 1), ('reumatologi', 1), ('LancetNCDs', 1), ('UNHLM', 1), ('NCDs', 1),
            ('NCDCountdown', 1), ('Säkerhet', 1), ('Patient', 1), ('MSD', 1), ('Läkemedel', 1),
            ('BästaPatientinformation', 1), ('Apotek', 1), ('gastricbypass', 1), ('FrågaDoktorn', 1),
            ('fetmanepidemin', 1), ('mediahusetkalmar', 1), ('tidning', 1), ('intervjuat', 1), ('skrivit', 1),
            ('barometern', 1), ('funktionsnedsättningar', 1), ('temadag', 1), ('lindrigutvecklingsstörning', 1),
            ('diagnoser', 1), ('högalidsfolkhögskola', 1), ('chorizo', 1), ('frittata', 1), ('myteromdiabetes', 1),
            ('braellerdåligaursäkter', 1), ('MariaWern', 1), ('Sahlgrenska', 1), ('biggestloser', 1), ('nyaaland', 1),
            ('hyrläkare', 1), ('Aktiedagen', 1), ('TIL', 1), ('DiamydMedical', 1), ('autoimmune', 1), ('Remygen', 1),
            ('flatliner', 1), ('analys', 1), ('Bouncecamp', 1), ('VarbergsDiabetesförening', 1), ('duellen', 1),
            ('mat2018', 1), ('matsmåland', 1), ('strokepatienter', 1), ('blodsockerfall', 1), ('Medicin', 1),
            ('Mat', 1), ('skitskaskitha', 1), ('honung', 1), ('probiotisk', 1), ('utansocker', 1), ('äppelkompott', 1),
            ('rågbröd', 1), ('kostfiber', 1), ('frukost', 1), ('knäckebröd', 1), ('havregrynsgröt', 1), ('Fullkorn', 1),
            ('diabetesochjag', 1), ('insulin4all', 1), ('gikt', 1), ('hjärtproblem', 1), ('blodtryck', 1),
            ('tandum', 1), ('ulceröscolit', 1), ('tarmproblem', 1), ('Crohns', 1), ('Parkinson', 1), ('psoriasis', 1),
            ('kroniskasjukdomar', 1), ('IBS', 1), ('tarmhälsa', 1), ('arbetsmarknad', 1), ('springibenen', 1),
            ('pepskola', 1), ('Follicums', 1), ('BioStockLive', 1), ('dinröst', 1), ('mindfulpodden', 1),
            ('podcast', 1), ('4timmar', 1), ('elpex3or', 1), ('rullskidor', 1), ('guide', 1), ('skiregion', 1),
            ('symptom', 1), ('MR', 1), ('tumör', 1), ('magnetröntgen', 1), ('Vegatus', 1), ('mybad', 1),
            ('huntingtonssjukdom', 1), ('alzheimerz', 1), ('fytinsyra', 1), ('fytater', 1), ('tillväxthämning', 1),
            ('hypogonadism', 1), ('zinkbrist', 1), ('InteFulltSåBraKurva', 1), ('mmmchoklad', 1), ('anotherone', 1),
            ('gött', 1), ('herewegoagain', 1), ('glukos', 1), ('allergi', 1), ('immunförsvaret', 1),
            ('fuckDiabetes', 1), ('Dios', 1), ('diabetessamverkansverige', 1), ('midnattsloppet2018', 1), ('sova', 1),
            ('älskalöpning', 1), ('trail', 1), ('longhair', 1), ('sote', 1), ('hälsomat', 1), ('veganmat', 1),
            ('glutenfriarecept', 1), ('vegetariskt', 1), ('histamin', 1), ('aktiespararna', 1), ('ADHDpodden', 1),
            ('patientröst', 1), ('Övervikt', 1), ('Kostråd', 1), ('Socialdemokrater', 1), ('Valfilm', 1),
            ('Faktaresistens', 1), ('Korvbröd', 1), ('diabiceps', 1), ('jamieoliver', 1), ('who', 1), ('gardening', 1),
            ('cooking', 1), ('soda', 1), ('sugarrush', 1), ('sugartax', 1), ('sugar', 1), ('korvstroganoff', 1),
            ('korv', 1), ('längtanäröver', 1), ('resanstartarnu', 1), ('SummerClassic2018', 1), ('jaghardiabetes', 1),
            ('Media', 1), ('SVT', 1), ('tankesmedjan', 1), ('båtliv', 1), ('jobbet', 1), ('värmen', 1), ('envist', 1),
            ('ThingsIWouldChangeAboutMyself', 1), ('ykköstyyppi', 1), ('karolinska', 1), ('måndag', 1), ('monday', 1),
            ('HN', 1), ('MentalHealth', 1), ('Mykey', 1), ('Kalcium', 1), ('Bukspottkörteln', 1), ('Betaceller', 1),
            ('Beta3subenheten', 1), ('dryck', 1), ('iskall', 1), ('slush', 1), ('melon', 1), ('vattenmelon', 1),
            ('DödaMig', 1), ('Stigmabase', 1), ('fotbollstränare', 1), ('runtastic', 1), ('gener', 1), ('stickers', 1),
            ('LIBRE', 1), ('facebook', 1), ('betternow', 1), ('charitystorm', 1), ('egeninsamling', 1), ('pump', 1),
            ('Sensor', 1), ('tränahemma', 1), ('sommarspring', 1), ('sommar', 1), ('almedalen2017', 1),
            ('diabetessköterska', 1), ('ta', 1), ('t1dstrong', 1), ('intervaller', 1), ('uppvärmning', 1),
            ('Hyperglykemi', 1), ('subtweetFTW', 1), ('Netflix', 1), ('jihdesdiabetes', 1), ('AnnaLenaBerggren', 1),
            ('Förbrukningshjälpmedel', 1), ('lokaltidningen', 1), ('välmående', 1), ('tecken', 1), ('kämparglöd', 1),
            ('utmaning', 1), ('miljö', 1), ('CocaCola', 1), ('plåster', 1), ('illustreradvetenskap', 1), ('illvet', 1),
            ('fjällturen', 1), ('obegripligkoppling', 1), ('Mardröm', 1), ('pannacotta', 1), ('pb', 1),
            ('diabetesscreening', 1), ('stockhlm', 1), ('svemed', 1), ('Iblandfårmanunnasig', 1), ('replot', 1),
            ('diabetestype1', 1), ('McDonalds', 1), ('Midsona', 1), ('Novonordisk', 1), ('YuvalNoahHarari', 1),
            ('brighterir', 1), ('jidhesbarmyarmy', 1), ('thaigryta', 1), ('kyckling', 1), ('diabetessucks', 1),
            ('SD2018', 1), ('MED18', 1), ('kvinnofrid', 1), ('arbetsskadad', 1), ('DeVårdLösa', 1),
            ('spetspatienter', 1), ('swedishmedtech', 1), ('uppsala', 1), ('hejasverige', 1),
            ('serendipitychallange', 1), ('eyalmedalen', 1), ('sjukvårdspol', 1), ('novonordisk', 1), ('jihde', 1),
            ('detbästamedAlmedalen', 1), ('allasamlade', 1), ('bästagänget', 1), ('WPPAC18', 1), ('Frankenstein', 1),
            ('robinbryntesson', 1), ('efterseparation', 1), ('sockertoppen2018', 1), ('ÖstersundsSjukhus', 1),
            ('Barnkliniken', 1), ('barndiabetesteamets', 1), ('LionsClub', 1), ('scepticism', 1), ('science', 1),
            ('insamling', 1), ('geengåva', 1), ('dubai', 1), ('hjärtochkärlsjukdomar', 1), ('Göteborg', 1),
            ('migranter', 1), ('invandring', 1), ('tuberkulos', 1), ('segregation', 1), ('resursnämnd', 1),
            ('Socialdemokraterna', 1), ('islamofobi', 1), ('rasism', 1), ('mångfald', 1), ('integration', 1),
            ('skattebetalare', 1), ('integrationsfiaskot', 1), ('Angered', 1), ('Kamelcentret', 1), ('Morelli', 1),
            ('Barndiabetes', 1), ('lovelife', 1), ('sparsör', 1), ('fiskgryta', 1), ('rinkeby', 1), ('Allsvenskan', 1)]

hashtags_over_40 = []

sizes = []
other = 0
for element in testList:
    if element[1] > 30:
        hashtags_over_40.append(element[0])
        sizes.append(element[1])
    else:
        if element[1] >= 5:
            other += 1

sizes.append(other)
hashtags_over_40.append("Others")
print(hashtags_over_40)
print(sizes)

plt.bar(hashtags_over_40, sizes, )

plt.show()
